name: Build EXE

on:
  push:
    branches:
      - new_page

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 获取 pip 缓存目录
        id: pip-cache
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: 缓存 pip 包
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 安装依赖
        run: |
          pip install -r requirements.txt

      - name: 安装 SiliconUI
        run: |
          git clone https://github.com/ChinaIceF/PyQt-SiliconUI.git
          cd PyQt-SiliconUI
          python setup.py install

      - name: 构建 EXE
        run: python setup.py build_exe

      - name: 打包构建结果
        run: |
          powershell Compress-Archive -Path build/* -DestinationPath build.zip

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: build-exe
          path: build.zip
